### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by rikako-yurino** [rikako-yurino/furima-34770#9]
# URL
https://furima-34770.herokuapp.com/
# Basic認証のIDとパスワード 
認証のID:  admin
パスワード :  2222

# 出品者用のメールアドレスとパスワード
メールアドレス:  test1@com
パスワード:  test123456

# 購入者用のメールアドレスとパスワード
メールアドレス:  test3@com
パスワード:  test123456

**Comment by runak25033** [comment]
ご提出ありがとうございます！

動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！


[修正依頼箇所]
必要な情報を適切に入力すると、新規登録/ログインができること

→現状、パスワード欄に、例えば「aaa111」など「6文字以上、半角英数字混合」の入力を行なっても、
　"Password Include both letters and numbers" と表示が出て、新規登録ができない状態です



修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A


なお、その他の箇所につきましては、ご修正頂いた後に追って確認をさせて頂きます。

**Comment by runak25033** [comment]
ご修正ありがとうございます！

動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！


[修正依頼箇所]
・クレジットカード決済ができる
　→現状、正しいクレジットカード情報を入れても　"Token can't be blank" の表示が出て購入ができない状況です

・本番環境で投稿した商品画像が、S3に保存されること
　→現状、S3への保存がなされていない模様です


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

なお、その他の箇所につきましては、ご修正頂いた後に追って確認をさせて頂きます。

**Comment by rikako-yurino** [comment]
@runak25033 さん
ご確認くださりありがとうございます！
下記２点修正いたしました。

・クレジットカード決済ができる
・本番環境で投稿した商品画像が、S3に保存されること

本番環境で試しに出品してみた為、DBをリセットいたしました。
お手数ですが再度ご確認をお願いいたします！

**Comment by runak25033** [comment]
ご修正ありがとうございました。

まず、「クレジットカード決済ができる」こちらは修正されておりました！

次に、「本番環境で投稿した商品画像が、S3に保存されること」ですが、
こちらは、まだご修正がなされていないように見受けられましたので、再度ご確認をお願い申し上げます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A


あとひといきです！がんばってください！

**Comment by rikako-yurino** [comment]
@runak25033 さん
ご確認ありがとうございます！
「本番環境で投稿した商品画像が、S3に保存されること」
上記１点、再度修正をしました。
お手数をお掛けしますが、ご確認お願いします。

**Comment by runak25033** [comment]
ご修正ありがとうございます‼︎

修正箇所の確認ができました。
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
<img width="916" alt="最終課題LGTM2" src="https://user-images.githubusercontent.com/79125420/111260428-1b6e5800-8664-11eb-94f2-15d3fef9d384.png">
